baseURL: "http://ludovic.rivallain.fr/git-book-kubernetes/"
languageCode: "en-us"
title: "My Kubernetes Book"

theme: "book"
# theme: "ace-documentation"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1


blackfriday:
  extensions:
    - hardLineBreak

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo: true

# Enable Google Analytics
# googleAnalytics: UA-5631150-8

# Enable global emoji support
enableEmoji: true

pygmentsCodeFences: true
pygmentsStyle: "monokailight"

# Site parameters
params:
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme: 'dark'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC: true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo: 'images/kubernetes_logo.svg'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection: '*'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: 'https://github.com/lrivallain/git-book-kubernetes'

  # Enable 'Edit this page' links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to the site directory.
  BookEditPath: 'edit/master'

  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: 'Jan 1, 2021'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch: true

  # (Optional, default true) Enables comments template on pages
  # By default partials/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  # BookComments: true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  # BookPortableLinks: true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
  # BookServiceWorker: true


  # ordersectionsby: "weight" # ordersectionsby: "title"
  # disableSearch: false # default is false
  # disableReadmoreNav: false # set true to hide prev/next navigation, default is false
  # highlightClientSide: false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
  # menushortcutsnewtab: true # set true to open shortcuts links to a new tab/window
  # site_logo: '/images/kubernetes_logo.svg'